#!/bin/bash

cd $(dirname $0)
trash dist-old
mv dist dist-old
python setup.py bdist_egg bdist_wheel sdist
if [ "$1" != "--build-only " -a "$1" != "-b" ]; then
    twine upload -s -i "dmv@springwater7.org" dist/*
fi
